### ISSUE TITLE
Issues with renv 0.17.0 and 0.17.1

### ISSUE THREAD

**Issue by zkamvar** [carpentries/sandpaper#406]
> **Note**
>
> We are leaving this issue open so that anyone who experiences issues know to upgrade {renv}

## Recommendation

It is recommended for users to use {renv} version >= 0.17.2 (currently on CRAN) OR {renv} version <= 0.16.0.

Please run `install.packages("renv")` from your R console to upgrade. 

-----------------------------------------

> **Note**
>
> What follows below are protocols for when {renv} version 0.17.2 was not yet on CRAN.'
> If you have {renv} version >= 0.17.2, then you do not need to do anything. 

### Test if you need to update your version of {renv}

To test if you need to update your version of {renv}, run this R code in your R console:

``` r
packageVersion("renv") > package_version("0.17.1")
#> [1] TRUE
```

If the result is `TRUE`, then you do not need to do anything. 

If the result is `FALSE`, then follow **one of** the steps below.

### Upgrading to the patched version: 0.17.0-38

To upgrade to the patched version of {renv}, use the following code to install [renv version 0.17.0-38 from The Carpentries R-universe](https://carpentries.r-universe.dev/renv). Note: this is the version that {sandpaper} will use to build your R Markdown lessons on GitHub.

```r
install.packages('renv', repos = c('https://carpentries.r-universe.dev', 'https://cloud.r-project.org'))
```

> **Note** 
> renv 0.17.1 has a bug with its package cache (see https://github.com/rstudio/renv/issues/1168) where the hashing changed. 
> **This has been fixed in 0.17.2.**

### Downgrading to 0.16.0

If you wish to downgrade {renv} instead, you can install {renv} from an archive:

```r
install.packages("https://cran.r-project.org/src/contrib/Archive/renv/renv_0.16.0.tar.gz")
```

## Problem

The new version of {renv} 0.17.0 introduced a few unexpected bugs:

1. The `renv/` folder now contains a locked sandbox folder, which causes [teardown errors](https://github.com/carpentries/sandpaper/actions/runs/4349232778/jobs/7598658989):
   ```
   rm: cannot remove '/tmp/Rtmp7JrJC1/Rbuild184d2b8b02c/sandpaper/renv/sandbox/R-4.2/x86_64-pc-linux-gnu/99f2a2ef/spatial': Permission denied
   ... snip ...
   rm: cannot remove '/tmp/Rtmp7JrJC1/Rbuild184d2b8b02c/sandpaper/renv/sandbox/R-4.2/x86_64-pc-linux-gnu/99f2a2ef/foreign': Permission denied
   ```
2. The welcome message has changed so our regex no longer works and causes [R CMD check to fail](https://github.com/carpentries/sandpaper/actions/runs/4349232778/jobs/7598658989#step:13:58):
   ```
   --- re-building ‘building-with-renv.Rmd’ using rmarkdown
   Quitting from lines 44-48 (building-with-renv.Rmd) 
   Error: Error: processing vignette 'building-with-renv.Rmd' failed with diagnostics:
   NA/NaN argument
   ```
3. BioConductor packages can no longer be provisioned or restored (see https://github.com/rstudio/renv/issues/1156)
4. Continuous Integration is failing in ways that I cannot debug at the moment (see https://github.com/rstudio/renv/issues/1161 and https://github.com/carpentries/sandpaper/pull/405)

## Lessons Affected

 - BioConductor Lessons can no longer restore their package cache
 - New R Markdown lessons can no longer add new packages to the cache

All other existing lessons should work as expected.

**Comment by zkamvar** [comment]
## Update

The issues presented have been fixed as of [{renv} 0.17.0-34](https://github.com/rstudio/renv/tree/0.17.0-34) :tada:

Point 1 has not yet been fully fixed (an attempt was made in https://github.com/rstudio/renv/commit/be9336a19b3bf7eff07f1a72de93bc5939b0f391), but it has not succeeded (https://github.com/rstudio/renv/issues/1158#issuecomment-1462416715) I have addressed it for R CMD check in 4f2a4ae056dda22a545293450a997b15df5b2ce5 by setting an external folder for the sandbox

Point 2 was easily addressed in c0f19a187ba3b571aca72ff277c06abe305965b5 and 75506e3953dcd7bbddd2bc467ec1a81555f86329, which updated the message parsing.

Point 3 was not explicitly a BioConductor bug and was addressed in https://github.com/rstudio/renv/commit/7aa92a0963a1d86357c85f22bf973429b2fae75e, which updated how r-universe repositories were handled.

Point 4 was fixed by https://github.com/rstudio/renv/commit/028ccc512b0c823fd2cea344f8c84968677edc2f and https://github.com/rstudio/renv/commit/c0688805a1f307ce0fffbcad7a25a8c0c473e170, which updated the way `R_LIBS_USER` envvars were validated and how hydrate provisions source libraries. 

## Tasks left

 - [ ] remove extra {renv} logging steps in https://github.com/carpentries/sandpaper/pull/405
 - [ ] fix https://github.com/carpentries/actions/issues/70
 - [ ] [update universe](https://github.com/carpentries/universe/blob/3838428be15d0a53cc9d7cbf30f9f28d217de8b0/packages.json#L16-L20) to use correct version of {renv}
 - [ ] ensure actions use correct version of {renv}

**Comment by zkamvar** [comment]
{renv} 0.17.1 has been released to CRAN. I will test this with the bioc lessons and then close this issue.

**Comment by zkamvar** [comment]
It does not break the bioc lessons, but #415 shows that there is something up with the reporting mechanism. 

In addition, the hashing mechanism appears to be different

**Comment by zkamvar** [comment]
> In addition, the hashing mechanism appears to be different

I see that someone else has noticed this: https://github.com/rstudio/renv/issues/1168

**Comment by zkamvar** [comment]
What this means is that, because we make sure to rebuild if the package cache file has changed

https://github.com/carpentries/sandpaper/blob/c8b911a4dda692d1f189ecec112ce83c1c90731d/inst/workflows/sandpaper-main.yaml#L59

then all R-based lessons will constantly go through a rebuild process until renv 0.17.2 is released.

**Comment by zkamvar** [comment]
As of {renv} 0.17.2, you do not need to do anything as long as your version of {sandpaper} is up-to-date

**Comment by zkamvar** [comment]
I believe this is no longer an issue, so I will close it hoping that others who face this problem will find their way here.
